### ISSUE TITLE
Add utility method to convert a Transformer to an Operator

### ISSUE THREAD

**Issue by davidmoten** [ReactiveX/RxJava#2865]
I have a documented API for [rxjava-jdbc](https://github.com/davidmoten/rxjava-jdbc) that suggests  certain special operations to be performed using the ```Observable.lift``` method with custom ```Operator```s.  Works fine but if internally I decide to use a composition of existing operators instead of a custom operator then I need the ability to convert a ```Transformer``` into an ```Operator``` so that the documented use of the API does not need to change.  I'd suggest the addition of a ```Transformers``` utility class and supporting classes: 

```java
public final class Transformers {

    public static <T,R> Operator<R,T> toOperator(Transformer<T,R> transformer) {
        return TransformerOperator.toOperator(transformer);
    }
    
}
```

I have the code for this and tests resident in *rxjava-jdbc* and can contribute it if there is support. Are people happy for me to proceed with a PR?

Incidentally, ```Operator``` -> ```Transformer``` is a trivial conversion, it is just the ```Transformer``` -> ```Operator``` conversion that the suggested PR could facilitate.

**Comment by adi1133** [comment]
I'd also like this enhancement

**Comment by akarnokd** [comment]
If we are talking about internal API changes, you should be able to replace the operator without any transformations:
```java
public Observable<T> someOperation() {
    return lift(new MyOperator());
}
// ...
public Observable<T> someOperator() {
    return this.subscribeOn(Schedulers.io()).observeOn(Schedulers.computation()).takeLast(1);
}
```

**Comment by davidmoten** [comment]
That's not what I'm after. A client has been told to process an Observable `o` like this:

`o.lift(thing.createOperator())......`

but I now want to change the implementation of `thing.createOperator()` so that it still returns an `Operator` but is based on a `Transformer` like

`o -> o.buffer(2).blah().blah()`

without the client having to change their usage.

This is how I implemented it for my own usage and I wondered if it should be part of the RxJava API:

https://github.com/davidmoten/rxjava-extras/blob/master/src/main/java/com/github/davidmoten/rx/operators/OperatorFromTransformer.java

**Comment by akarnokd** [comment]
I'm still not convinced this is transformation should be part of the public API.

**Comment by davidmoten** [comment]
Righto, feature is in [rxjava-extras](https://github.com/davidmoten/rxjava-extras) (`Transformers.toOperator`) if anyone wants it.
